title: Noah Pistilli
email: noah@wiilink.ca
description: >- # this means to ignore newlines until "baseurl:"
  Site about my projects and where my blog is hosted.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://noahpistilli.ca" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: noah.pistilli
github_username:  noahpistilli

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
 - _pages
 - _data
 - _layouts
 - _includes

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/noahpistilli"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/noah.pistilli"